/**
 * This file was autogenerated.
 * All changes will be lost next time FuncArg
 * Templates are updated!
 */

using CBRoomConverter.Reflection;

namespace CBRoomConverter.FunctionArguments;

[BlitzFuncArgs( "CreatePivot" )]
internal class CreatePivotFuncArgs : BaseFuncArgs
{
	[BlitzFuncArgIndex( "parent", 0, Optional: true )]
	public string? parent { get; set; }
}
