/**
 * This file was autogenerated.
 * All changes will be lost next time FuncArg
 * Templates are updated!
 */

using CBRoomConverter.Reflection;

namespace CBRoomConverter.FunctionArguments;

[BlitzFuncArgs( "EntityParent" )]
internal class EntityParentFuncArgs : BaseFuncArgs
{
	[BlitzFuncArgIndex( "entity", 0, Optional: false )]
	public required string entity { get; set; }

	[BlitzFuncArgIndex( "parent", 1, Optional: false )]
	public required string parent { get; set; }

	[BlitzFuncArgIndex( "global", 2, Optional: true )]
	public string? global { get; set; }
}
