/**
 * This file was autogenerated.
 * All changes will be lost next time FuncArg
 * Templates are updated!
 */

using CBRoomConverter.Reflection;

namespace CBRoomConverter.FunctionArguments;

[BlitzFuncArgs( "ScaleEntity" )]
internal class ScaleEntityFuncArgs : BaseFuncArgs
{
	[BlitzFuncArgIndex( "entity", 0, Optional: false )]
	public required string entity { get; set; }

	[BlitzFuncArgIndex( "x_scale", 1, Optional: false )]
	public required string x_scale { get; set; }

	[BlitzFuncArgIndex( "y_scale", 2, Optional: false )]
	public required string y_scale { get; set; }

	[BlitzFuncArgIndex( "z_scale", 3, Optional: false )]
	public required string z_scale { get; set; }

	[BlitzFuncArgIndex( "global", 4, Optional: true )]
	public string? global { get; set; }
}
