/**
 * This file was autogenerated.
 * All changes will be lost next time FuncArg
 * Templates are updated!
 */

using CBRoomConverter.Reflection;

namespace CBRoomConverter.FunctionArguments;

[BlitzFuncArgs( "TurnEntity" )]
internal class TurnEntityFuncArgs : BaseFuncArgs
{
	[BlitzFuncArgIndex( "entity", 0, Optional: false )]
	public required string entity { get; set; }

	[BlitzFuncArgIndex( "pitch", 1, Optional: false )]
	public required string pitch { get; set; }

	[BlitzFuncArgIndex( "yaw", 2, Optional: false )]
	public required string yaw { get; set; }

	[BlitzFuncArgIndex( "roll", 3, Optional: false )]
	public required string roll { get; set; }

	[BlitzFuncArgIndex( "global", 4, Optional: true )]
	public string? global { get; set; }
}
