/**
 * This file was autogenerated.
 * All changes will be lost next time FuncArg
 * Templates are updated!
 */

using CBRoomConverter.Reflection;

namespace CBRoomConverter.FunctionArguments;

[BlitzFuncArgs( "{{FUNC_NAME}}" )]
internal class {{CLASS_NAME}} : BaseFuncArgs
{
{{FUNCTIONS}}
}
